* =resource=
Resources are the most important element in
the Terraform language. Each resource block
describes one or more infrastructure objects,
such as virtual networks, compute instances,
or higher-level components such as DNS
records.

** Resource Blocks
https://www.terraform.io/docs/language/resources/syntax.html

documents the syntax for declaring resources.

** Resource Behavior
https://www.terraform.io/docs/language/resources/behavior.html

explains in more detail how Terraform handles
resource declarations when applying a configuration.

** The Meta-Arguments section
https://www.terraform.io/docs/language/resources/provisioners/index.html

documents special arguments that can be
 used with every resource type, including depends_on, count,
 for_each, provider, and lifecycle.

** Provisioners
documents configuring post-creation actions
for a resource using the provisioner and
connection blocks. Since provisioners are non-
declarative and potentially unpredictable, we
strongly recommend that you treat them as a
last resort.